# default parameters for lane_filter/lane_filter_node
mean_d_0: 0
mean_phi_0: 0
sigma_d_0: 0.1
sigma_phi_0: 0.1
delta_d: 0.02
delta_phi: 0.05
d_max: 0.3
d_min: -0.15
phi_min: -1.5
phi_max: 1.5
cov_v: 0.5
cov_omega: 0.01
linewidth_white: 0.05
linewidth_yellow: 0.025
lanewidth: 0.20
min_max: 0.1

# minimum number of segments for generating measurement:
use_min_segs: False
min_segs: 10

# maximum segment distance:
use_max_segment_dist: False
max_segment_dist: 0.3

# distance weighting:
use_distance_weighting: False
zero_val: 1
l_peak: 1
peak_val: 10
l_max: 2

#propagation
use_propagation: False
sigma_d_mask: 0.05
sigma_phi_mask: 0.05

# LINE DETECTION
img_size: [120,160]
top_cutoff: 40

# should be an array of 2 elements. The first is the name of the class
# and the second should be the parameters. 
# The class should be an abstract instance of LineDetectorInterface
detector: 
  - line_detector.LineDetectorHSV
  - configuration:
      dilation_kernel_size: 3
      canny_thresholds: [80,200]
      hough_threshold: 20
      hough_min_line_length: 3
      hough_max_line_gap:    1
     
      hsv_white1:  [0,0,150]
      hsv_white2:  [180,60,255]
      hsv_yellow1: [25,140,100]
      hsv_yellow2: [45,255,255]
      hsv_red1:    [0,140,100]
      hsv_red2:    [15,255,255]
      hsv_red3:    [165,140,100]
      hsv_red4:    [180,255,255]