//This file is automatically generated. DO NOT EDIT!

#include <RobotRaconteur.h>
#include <boost/signals2.hpp>
#pragma once

namespace Duckiebot
{
namespace LaneInfo
{

class LanePose;
class LaneInfo;

class LanePose : public RobotRaconteur::RRStructure {
public:
double d;
double sigma_d;
double phi;
double sigma_phi;
uint8_t in_lane;

virtual std::string RRType() {return "Duckiebot.LaneInfo.LanePose";  }
};

class LaneInfo : public virtual RobotRaconteur::RRObject
{
public:
virtual RR_SHARED_PTR<LanePose > get_lanePose()=0;
virtual void set_lanePose(RR_SHARED_PTR<LanePose > value)=0;

virtual std::string RRType() {return "Duckiebot.LaneInfo.LaneInfo";  }
};

}
}

