//This file is automatically generated. DO NOT EDIT!

#ifndef ROBOTRACONTEUR_USE_STDAFX
#include "Duckiebot__GroundProjection_stubskel.h"
#include <boost/algorithm/string.hpp>
#include <boost/lexical_cast.hpp>
#else
#include "stdafx.h"
#endif
namespace Duckiebot
{
namespace GroundProjection
{
std::string Duckiebot__GroundProjectionFactory::GetServiceName()
{
return "Duckiebot.GroundProjection";
}
std::string Duckiebot__GroundProjectionFactory::DefString()
{
std::string out(
"#Service to provide interface to projection of lines onto the ground\n"
"service Duckiebot.GroundProjection\n"
"\n"
"option version 0.8\n"
"\n"
"import Duckiebot\n"
"\n"
"object GroundProjection\n"
"property Duckiebot.Segment{list} segments\n"
"\n"
"function double[] estimate_homography(Duckiebot.Image im)\n"
"function Duckiebot.Point ground_coordinate(Duckiebot.Pixel uv, Duckiebot.Vector2D normalized_uv)\n"
"function Duckiebot.Vector2D image_coordinate(Duckiebot.Point gp)\n"
"\n"
"# likely want some way of clients only checking when new segments found.\n"
"event newSegments(Duckiebot.Segment{list} segs)\n"
"end object\n"
);
return out;
}
RR_SHARED_PTR<RobotRaconteur::StructureStub> Duckiebot__GroundProjectionFactory::FindStructureStub(std::string s)
{
boost::tuple<std::string,std::string> res=RobotRaconteur::SplitQualifiedName(s);
std::string servicetype=res.get<0>();
std::string objecttype=res.get<1>();
throw RobotRaconteur::ServiceException("Invalid structure stub type.");
}
RR_SHARED_PTR<RobotRaconteur::MessageElementStructure> Duckiebot__GroundProjectionFactory::PackStructure(RR_SHARED_PTR<RobotRaconteur::RRStructure> structin)
{
std::string type=structin->RRType();boost::tuple<std::string,std::string> res=RobotRaconteur::SplitQualifiedName(type);
std::string servicetype=res.get<0>();
std::string objecttype=res.get<1>();
if (servicetype != "Duckiebot.GroundProjection") return GetNode()->PackStructure(structin);
RR_SHARED_PTR<RobotRaconteur::StructureStub> stub=FindStructureStub(type);
return stub->PackStructure(structin);
throw RobotRaconteur::ServiceException("Invalid structure stub type.");
}
RR_SHARED_PTR<RobotRaconteur::RRObject> Duckiebot__GroundProjectionFactory::UnpackStructure(RR_SHARED_PTR<RobotRaconteur::MessageElementStructure> mstructin)
{
std::string type=mstructin->GetTypeString();boost::tuple<std::string,std::string> res=RobotRaconteur::SplitQualifiedName(type);
std::string servicetype=res.get<0>();
std::string objecttype=res.get<1>();
if (servicetype != "Duckiebot.GroundProjection") return GetNode()->UnpackStructure(mstructin);
RR_SHARED_PTR<RobotRaconteur::StructureStub> stub=FindStructureStub(type);
return stub->UnpackStructure(mstructin);
throw RobotRaconteur::ServiceException("Invalid structure stub type.");
}
RR_SHARED_PTR<RobotRaconteur::ServiceStub> Duckiebot__GroundProjectionFactory::CreateStub(std::string type, std::string path, RR_SHARED_PTR<RobotRaconteur::ClientContext> context)
{
boost::tuple<std::string,std::string> res=RobotRaconteur::SplitQualifiedName(type);
std::string servicetype=res.get<0>();
std::string objecttype=res.get<1>();
if (servicetype != "Duckiebot.GroundProjection") return GetNode()->GetServiceType(servicetype)->CreateStub(type,path,context);
if (objecttype=="GroundProjection") { RR_SHARED_PTR<GroundProjection_stub> o=(RR_MAKE_SHARED<GroundProjection_stub>(path,context)); o->RRInitStub(); return o; }
throw RobotRaconteur::ServiceException("Invalid structure stub type.");
}
RR_SHARED_PTR<RobotRaconteur::ServiceSkel> Duckiebot__GroundProjectionFactory::CreateSkel(std::string type, std::string path, RR_SHARED_PTR<RobotRaconteur::RRObject> obj, RR_SHARED_PTR<RobotRaconteur::ServerContext> context)
{
boost::tuple<std::string,std::string> res=RobotRaconteur::SplitQualifiedName(type);
std::string servicetype=res.get<0>();
std::string objecttype=res.get<1>();
if (servicetype != "Duckiebot.GroundProjection") return GetNode()->GetServiceType(servicetype)->CreateSkel(type,path,obj,context);
if (objecttype=="GroundProjection") {RR_SHARED_PTR<GroundProjection_skel> o=RR_MAKE_SHARED<GroundProjection_skel>(); o->Init(path,obj,context); return o; }
throw RobotRaconteur::ServiceException("Invalid structure skel type.");
return RR_SHARED_PTR<RobotRaconteur::ServiceSkel>();
}
void Duckiebot__GroundProjectionFactory::DownCastAndThrowException(RobotRaconteur::RobotRaconteurException& rr_exp)
{
std::string rr_type=rr_exp.Error;
if (rr_type.find('.')==std::string::npos)
{
	return;
}
boost::tuple<std::string,std::string> rr_res=RobotRaconteur::SplitQualifiedName(rr_type);
if (rr_res.get<0>() != "Duckiebot.GroundProjection") GetNode()->DownCastAndThrowException(rr_exp);
return;
}
RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> Duckiebot__GroundProjectionFactory::DownCastException(RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> rr_exp){
if (!rr_exp) return rr_exp;
std::string rr_type=rr_exp->Error;
if (rr_type.find('.')==std::string::npos)
{
	return rr_exp;
}
boost::tuple<std::string,std::string> rr_res=RobotRaconteur::SplitQualifiedName(rr_type);
if (rr_res.get<0>() != "Duckiebot.GroundProjection") return GetNode()->DownCastException(rr_exp);
return rr_exp;
}

GroundProjection_stub::GroundProjection_stub(const std::string &path, RR_SHARED_PTR<RobotRaconteur::ClientContext> c) : RobotRaconteur::ServiceStub(path,c){ }
void GroundProjection_stub::RRInitStub()
{
}

RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > GroundProjection_stub::get_segments()
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> m=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_PropertyGetReq,"segments");
RR_SHARED_PTR<RobotRaconteur::MessageEntry> mr=ProcessTransaction(m);
RR_SHARED_PTR<RobotRaconteur::MessageElement> me=mr->FindElement("value");
return RobotRaconteur::rr_cast<RobotRaconteur::RRList<Duckiebot::Segment  > >((RRGetNode()->UnpackListType<Duckiebot::Segment  >(me->CastData<RobotRaconteur::MessageElementList >())));
}
void GroundProjection_stub::set_segments(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> req=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_PropertySetReq,"segments");
req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("value",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackListType<Duckiebot::Segment  >(value))));
RR_SHARED_PTR<RobotRaconteur::MessageEntry> mr=ProcessTransaction(req);
}

RR_SHARED_PTR<RobotRaconteur::RRArray<double > > GroundProjection_stub::estimate_homography(RR_SHARED_PTR<Duckiebot::Image > im)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_req=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_FunctionCallReq,"estimate_homography");
rr_req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("im",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(im)))));
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_ret=ProcessTransaction(rr_req);
RR_SHARED_PTR<RobotRaconteur::MessageElement> rr_me=rr_ret->FindElement("return");
return rr_me->CastData<RobotRaconteur::RRArray<double > >();
}

RR_SHARED_PTR<Duckiebot::Point > GroundProjection_stub::ground_coordinate(RR_SHARED_PTR<Duckiebot::Pixel > uv, RR_SHARED_PTR<Duckiebot::Vector2D > normalized_uv)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_req=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_FunctionCallReq,"ground_coordinate");
rr_req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("uv",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(uv)))));
rr_req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("normalized_uv",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(normalized_uv)))));
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_ret=ProcessTransaction(rr_req);
RR_SHARED_PTR<RobotRaconteur::MessageElement> rr_me=rr_ret->FindElement("return");
return RobotRaconteur::rr_cast<Duckiebot::Point >(RRGetNode()->UnpackStructure(rr_me->CastData<RobotRaconteur::MessageElementStructure>()));
}

RR_SHARED_PTR<Duckiebot::Vector2D > GroundProjection_stub::image_coordinate(RR_SHARED_PTR<Duckiebot::Point > gp)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_req=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_FunctionCallReq,"image_coordinate");
rr_req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("gp",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(gp)))));
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_ret=ProcessTransaction(rr_req);
RR_SHARED_PTR<RobotRaconteur::MessageElement> rr_me=rr_ret->FindElement("return");
return RobotRaconteur::rr_cast<Duckiebot::Vector2D >(RRGetNode()->UnpackStructure(rr_me->CastData<RobotRaconteur::MessageElementStructure>()));
}

boost::signals2::signal<void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >)>& GroundProjection_stub::get_newSegments()
{
return rrvar_newSegments;
}

void GroundProjection_stub::DispatchEvent(RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_m)
{
if (rr_m->MemberName=="newSegments")
{
RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > segs=RobotRaconteur::rr_cast<RobotRaconteur::RRList<Duckiebot::Segment  > >((RRGetNode()->UnpackListType<Duckiebot::Segment  >(rr_m->FindElement("segs")->CastData<RobotRaconteur::MessageElementList >())));
get_newSegments()(segs);
return;
}
throw RobotRaconteur::MemberNotFoundException("Member not found");
}
void GroundProjection_stub::DispatchPipeMessage(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m)
{
throw RobotRaconteur::MemberNotFoundException("Member not found");
}
void GroundProjection_stub::DispatchWireMessage(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m)
{
throw RobotRaconteur::MemberNotFoundException("Member not found");
}
RR_SHARED_PTR<RobotRaconteur::MessageEntry>GroundProjection_stub::CallbackCall(RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_m)
{
std::string ename=rr_m->MemberName;
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_mr=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_CallbackCallRet, ename);
rr_mr->ServicePath=rr_m->ServicePath;
rr_mr->TransactionID=rr_m->TransactionID;
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

std::string GroundProjection_stub::RRType()
{
return "Duckiebot.GroundProjection.GroundProjection";
}
void GroundProjection_stub::RRClose()
{
rrvar_newSegments.disconnect_all_slots();
ServiceStub::RRClose();
}

void GroundProjection_stub::async_get_segments(boost::function<void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> m=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_PropertyGetReq,"segments");
AsyncProcessTransaction(m,boost::bind(&GroundProjection_stub::rrend_get_segments, RobotRaconteur::rr_cast<GroundProjection_stub>(shared_from_this()),_1,_2,rr_handler ),rr_timeout);
}
void GroundProjection_stub::rrend_get_segments(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > ,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler)
{
if (err)
{
handler(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >(),err);
return;
}
if (m->Error != RobotRaconteur::MessageErrorType_None)
{
handler(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >(),RobotRaconteur::RobotRaconteurExceptionUtil::MessageEntryToException(m));
return;
}
RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > rr_ret;
try
{
RR_SHARED_PTR<RobotRaconteur::MessageElement> me=m->FindElement("value");
rr_ret=RobotRaconteur::rr_cast<RobotRaconteur::RRList<Duckiebot::Segment  > >((RRGetNode()->UnpackListType<Duckiebot::Segment  >(me->CastData<RobotRaconteur::MessageElementList >())));
}
catch (RobotRaconteur::RobotRaconteurException& err)
{
handler(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >(),RobotRaconteur::RobotRaconteurExceptionUtil::DownCastException(err));
return;
}
catch (std::exception& err)
{
handler(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >(),RR_MAKE_SHARED<RobotRaconteur::RobotRaconteurRemoteException>(std::string(typeid(err).name()),err.what()));
return;
}
handler(rr_ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>());
}
void GroundProjection_stub::async_set_segments(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value,boost::function<void (RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> req=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_PropertySetReq,"segments");
req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("value",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackListType<Duckiebot::Segment  >(value))));
AsyncProcessTransaction(req,boost::bind(&GroundProjection_stub::rrend_set_segments, RobotRaconteur::rr_cast<GroundProjection_stub>(shared_from_this()),_1,_2,rr_handler ),rr_timeout);
}
void GroundProjection_stub::rrend_set_segments(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler)
{
if (err)
{
handler(err);
return;
}
if (m->Error != RobotRaconteur::MessageErrorType_None)
{
handler(RobotRaconteur::RobotRaconteurExceptionUtil::MessageEntryToException(m));
return;
}
handler(RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>());
}
void GroundProjection_stub::async_estimate_homography(RR_SHARED_PTR<Duckiebot::Image > im,boost::function<void (RR_SHARED_PTR<RobotRaconteur::RRArray<double > >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_req=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_FunctionCallReq,"estimate_homography");
rr_req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("im",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(im)))));
AsyncProcessTransaction(rr_req,boost::bind(&GroundProjection_stub::rrend_estimate_homography, RobotRaconteur::rr_cast<GroundProjection_stub>(shared_from_this()),_1,_2,rr_handler ),rr_timeout);
}

void GroundProjection_stub::rrend_estimate_homography(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<RobotRaconteur::RRArray<double > > ,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler)
{
if (err)
{
handler(RR_SHARED_PTR<RobotRaconteur::RRArray<double > >(),err);
return;
}
if (m->Error != RobotRaconteur::MessageErrorType_None)
{
handler(RR_SHARED_PTR<RobotRaconteur::RRArray<double > >(),RobotRaconteur::RobotRaconteurExceptionUtil::MessageEntryToException(m));
return;
}
RR_SHARED_PTR<RobotRaconteur::RRArray<double > > rr_ret;
try
{
RR_SHARED_PTR<RobotRaconteur::MessageElement> me=m->FindElement("return");
rr_ret=me->CastData<RobotRaconteur::RRArray<double > >();
}
catch (RobotRaconteur::RobotRaconteurException& err)
{
handler(RR_SHARED_PTR<RobotRaconteur::RRArray<double > >(),RobotRaconteur::RobotRaconteurExceptionUtil::DownCastException(err));
return;
}
catch (std::exception& err)
{
handler(RR_SHARED_PTR<RobotRaconteur::RRArray<double > >(),RR_MAKE_SHARED<RobotRaconteur::RobotRaconteurRemoteException>(std::string(typeid(err).name()),err.what()));
return;
}
handler(rr_ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>());
}
void GroundProjection_stub::async_ground_coordinate(RR_SHARED_PTR<Duckiebot::Pixel > uv, RR_SHARED_PTR<Duckiebot::Vector2D > normalized_uv,boost::function<void (RR_SHARED_PTR<Duckiebot::Point >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_req=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_FunctionCallReq,"ground_coordinate");
rr_req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("uv",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(uv)))));
rr_req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("normalized_uv",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(normalized_uv)))));
AsyncProcessTransaction(rr_req,boost::bind(&GroundProjection_stub::rrend_ground_coordinate, RobotRaconteur::rr_cast<GroundProjection_stub>(shared_from_this()),_1,_2,rr_handler ),rr_timeout);
}

void GroundProjection_stub::rrend_ground_coordinate(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<Duckiebot::Point > ,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler)
{
if (err)
{
handler(RR_SHARED_PTR<Duckiebot::Point >(),err);
return;
}
if (m->Error != RobotRaconteur::MessageErrorType_None)
{
handler(RR_SHARED_PTR<Duckiebot::Point >(),RobotRaconteur::RobotRaconteurExceptionUtil::MessageEntryToException(m));
return;
}
RR_SHARED_PTR<Duckiebot::Point > rr_ret;
try
{
RR_SHARED_PTR<RobotRaconteur::MessageElement> me=m->FindElement("return");
rr_ret=RobotRaconteur::rr_cast<Duckiebot::Point >(RRGetNode()->UnpackStructure(me->CastData<RobotRaconteur::MessageElementStructure>()));
}
catch (RobotRaconteur::RobotRaconteurException& err)
{
handler(RR_SHARED_PTR<Duckiebot::Point >(),RobotRaconteur::RobotRaconteurExceptionUtil::DownCastException(err));
return;
}
catch (std::exception& err)
{
handler(RR_SHARED_PTR<Duckiebot::Point >(),RR_MAKE_SHARED<RobotRaconteur::RobotRaconteurRemoteException>(std::string(typeid(err).name()),err.what()));
return;
}
handler(rr_ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>());
}
void GroundProjection_stub::async_image_coordinate(RR_SHARED_PTR<Duckiebot::Point > gp,boost::function<void (RR_SHARED_PTR<Duckiebot::Vector2D >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_req=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_FunctionCallReq,"image_coordinate");
rr_req->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("gp",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(gp)))));
AsyncProcessTransaction(rr_req,boost::bind(&GroundProjection_stub::rrend_image_coordinate, RobotRaconteur::rr_cast<GroundProjection_stub>(shared_from_this()),_1,_2,rr_handler ),rr_timeout);
}

void GroundProjection_stub::rrend_image_coordinate(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<Duckiebot::Vector2D > ,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler)
{
if (err)
{
handler(RR_SHARED_PTR<Duckiebot::Vector2D >(),err);
return;
}
if (m->Error != RobotRaconteur::MessageErrorType_None)
{
handler(RR_SHARED_PTR<Duckiebot::Vector2D >(),RobotRaconteur::RobotRaconteurExceptionUtil::MessageEntryToException(m));
return;
}
RR_SHARED_PTR<Duckiebot::Vector2D > rr_ret;
try
{
RR_SHARED_PTR<RobotRaconteur::MessageElement> me=m->FindElement("return");
rr_ret=RobotRaconteur::rr_cast<Duckiebot::Vector2D >(RRGetNode()->UnpackStructure(me->CastData<RobotRaconteur::MessageElementStructure>()));
}
catch (RobotRaconteur::RobotRaconteurException& err)
{
handler(RR_SHARED_PTR<Duckiebot::Vector2D >(),RobotRaconteur::RobotRaconteurExceptionUtil::DownCastException(err));
return;
}
catch (std::exception& err)
{
handler(RR_SHARED_PTR<Duckiebot::Vector2D >(),RR_MAKE_SHARED<RobotRaconteur::RobotRaconteurRemoteException>(std::string(typeid(err).name()),err.what()));
return;
}
handler(rr_ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>());
}

void GroundProjection_skel::Init(const std::string& path, RR_SHARED_PTR<RobotRaconteur::RRObject> object, RR_SHARED_PTR<RobotRaconteur::ServerContext> context)
{
uncastobj=object;
rr_InitPipeServersRun=false;
rr_InitWireServersRun=false;
ServiceSkel::Init(path,object,context);
}
RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection > GroundProjection_skel::get_obj()
{
return RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection >(uncastobj);
}
RR_SHARED_PTR<Duckiebot::GroundProjection::async_GroundProjection > GroundProjection_skel::get_asyncobj()
{
return RR_DYNAMIC_POINTER_CAST<Duckiebot::GroundProjection::async_GroundProjection >(uncastobj);
}
void GroundProjection_skel::ReleaseCastObject() 
{
}
std::string GroundProjection_skel::GetObjectType()
{
return "Duckiebot.GroundProjection.GroundProjection";
}
RR_SHARED_PTR<RobotRaconteur::MessageEntry> GroundProjection_skel::CallGetProperty(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> mr=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_PropertyGetRes,m->MemberName);
RR_SHARED_PTR<Duckiebot::GroundProjection::async_GroundProjection > async_obj=get_asyncobj();
if (m->MemberName == "segments")
{
if (async_obj)
{
RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> wp=RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection_skel>(shared_from_this());
async_obj->async_get_segments(boost::bind(&Duckiebot::GroundProjection::GroundProjection_skel::rr_get_segments,wp,_1,_2,m,RobotRaconteur::ServerEndpoint::GetCurrentEndpoint()));
return RR_SHARED_PTR<RobotRaconteur::MessageEntry>();
}
else
{
RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value=get_obj()->get_segments();
mr->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("value",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackListType<Duckiebot::Segment  >(value))));
return mr;
}
}
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

RR_SHARED_PTR<RobotRaconteur::MessageEntry> GroundProjection_skel::CallSetProperty(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> mr=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_PropertySetRes,m->MemberName);
RR_SHARED_PTR<Duckiebot::GroundProjection::async_GroundProjection > async_obj=get_asyncobj();
if (m->MemberName == "segments")
{
RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value=RobotRaconteur::rr_cast<RobotRaconteur::RRList<Duckiebot::Segment  > >((RRGetNode()->UnpackListType<Duckiebot::Segment  >(m->FindElement("value")->CastData<RobotRaconteur::MessageElementList >())));
if (async_obj)
{
RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> wp=RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection_skel>(shared_from_this());
async_obj->async_set_segments(value,boost::bind(&RobotRaconteur::ServiceSkel::EndAsyncCallSetProperty,wp,_1,m,RobotRaconteur::ServerEndpoint::GetCurrentEndpoint()));
return RR_SHARED_PTR<RobotRaconteur::MessageEntry>();
}
else
{
get_obj()->set_segments(value);
return mr;
}
}
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

void GroundProjection_skel::rr_get_segments(RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel,RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::ServerEndpoint> ep)
{
if(err)
{
EndAsyncCallGetProperty(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),err,m, ep);
return;
}
try
{
RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel1=skel.lock();
if (!skel1) throw std::runtime_error("skel release");
RR_SHARED_PTR<RobotRaconteur::MessageElement> mr=RR_MAKE_SHARED<RobotRaconteur::MessageElement>("value",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(skel1->RRGetNode()->PackListType<Duckiebot::Segment  >(value)));
EndAsyncCallGetProperty(skel, mr, err, m,ep);
}
catch (RobotRaconteur::RobotRaconteurException& err2)
{
EndAsyncCallGetProperty(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),RobotRaconteur::RobotRaconteurExceptionUtil::DownCastException(err2),m, ep);
}
catch (std::exception& err2)
{
EndAsyncCallGetProperty(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),RR_MAKE_SHARED<RobotRaconteur::DataTypeException>(err2.what()),m, ep);
}
}
RR_SHARED_PTR<RobotRaconteur::MessageEntry> GroundProjection_skel::CallFunction(RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_m)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_mr=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_FunctionCallRes,rr_m->MemberName);
RR_SHARED_PTR<Duckiebot::GroundProjection::async_GroundProjection > async_obj=get_asyncobj();
if (rr_m->MemberName == "estimate_homography")
{
RR_SHARED_PTR<Duckiebot::Image > im =RobotRaconteur::rr_cast<Duckiebot::Image >(RRGetNode()->UnpackStructure(rr_m->FindElement("im")->CastData<RobotRaconteur::MessageElementStructure>()));
if (async_obj)
{
RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> rr_wp=RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection_skel>(shared_from_this());
async_obj->async_estimate_homography(im, boost::bind(&Duckiebot::GroundProjection::GroundProjection_skel::rr_estimate_homography, rr_wp, _1, _2, rr_m, RobotRaconteur::ServerEndpoint::GetCurrentEndpoint()));
return RR_SHARED_PTR<RobotRaconteur::MessageEntry>();
}
else
{
RR_SHARED_PTR<RobotRaconteur::RRArray<double > > rr_return=get_obj()->estimate_homography(im);
rr_mr->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("return",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(rr_return)));
return rr_mr;
}
}
if (rr_m->MemberName == "ground_coordinate")
{
RR_SHARED_PTR<Duckiebot::Pixel > uv =RobotRaconteur::rr_cast<Duckiebot::Pixel >(RRGetNode()->UnpackStructure(rr_m->FindElement("uv")->CastData<RobotRaconteur::MessageElementStructure>()));
RR_SHARED_PTR<Duckiebot::Vector2D > normalized_uv =RobotRaconteur::rr_cast<Duckiebot::Vector2D >(RRGetNode()->UnpackStructure(rr_m->FindElement("normalized_uv")->CastData<RobotRaconteur::MessageElementStructure>()));
if (async_obj)
{
RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> rr_wp=RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection_skel>(shared_from_this());
async_obj->async_ground_coordinate(uv, normalized_uv, boost::bind(&Duckiebot::GroundProjection::GroundProjection_skel::rr_ground_coordinate, rr_wp, _1, _2, rr_m, RobotRaconteur::ServerEndpoint::GetCurrentEndpoint()));
return RR_SHARED_PTR<RobotRaconteur::MessageEntry>();
}
else
{
RR_SHARED_PTR<Duckiebot::Point > rr_return=get_obj()->ground_coordinate(uv, normalized_uv);
rr_mr->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("return",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(rr_return)))));
return rr_mr;
}
}
if (rr_m->MemberName == "image_coordinate")
{
RR_SHARED_PTR<Duckiebot::Point > gp =RobotRaconteur::rr_cast<Duckiebot::Point >(RRGetNode()->UnpackStructure(rr_m->FindElement("gp")->CastData<RobotRaconteur::MessageElementStructure>()));
if (async_obj)
{
RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> rr_wp=RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection_skel>(shared_from_this());
async_obj->async_image_coordinate(gp, boost::bind(&Duckiebot::GroundProjection::GroundProjection_skel::rr_image_coordinate, rr_wp, _1, _2, rr_m, RobotRaconteur::ServerEndpoint::GetCurrentEndpoint()));
return RR_SHARED_PTR<RobotRaconteur::MessageEntry>();
}
else
{
RR_SHARED_PTR<Duckiebot::Vector2D > rr_return=get_obj()->image_coordinate(gp);
rr_mr->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("return",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(rr_return)))));
return rr_mr;
}
}
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

void GroundProjection_skel::rr_estimate_homography(RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel, RR_SHARED_PTR<RobotRaconteur::RRArray<double > > ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::ServerEndpoint> ep)
{
if(err)
{
EndAsyncCallFunction(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),err,m, ep);
return;
}
try
{
RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel1=skel.lock();
if (!skel1) throw std::runtime_error("skel release");
RR_SHARED_PTR<RobotRaconteur::MessageElement> mr=RR_MAKE_SHARED<RobotRaconteur::MessageElement>("return",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(ret));
EndAsyncCallFunction(skel, mr, err, m,ep);
}
catch (RobotRaconteur::RobotRaconteurException& err2)
{
EndAsyncCallFunction(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),RobotRaconteur::RobotRaconteurExceptionUtil::DownCastException(err2),m, ep);
}
catch (std::exception& err2)
{
EndAsyncCallFunction(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),RR_MAKE_SHARED<RobotRaconteur::DataTypeException>(err2.what()),m, ep);
}
}
void GroundProjection_skel::rr_ground_coordinate(RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel, RR_SHARED_PTR<Duckiebot::Point > ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::ServerEndpoint> ep)
{
if(err)
{
EndAsyncCallFunction(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),err,m, ep);
return;
}
try
{
RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel1=skel.lock();
if (!skel1) throw std::runtime_error("skel release");
RR_SHARED_PTR<RobotRaconteur::MessageElement> mr=RR_MAKE_SHARED<RobotRaconteur::MessageElement>("return",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(skel1->RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(ret))));
EndAsyncCallFunction(skel, mr, err, m,ep);
}
catch (RobotRaconteur::RobotRaconteurException& err2)
{
EndAsyncCallFunction(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),RobotRaconteur::RobotRaconteurExceptionUtil::DownCastException(err2),m, ep);
}
catch (std::exception& err2)
{
EndAsyncCallFunction(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),RR_MAKE_SHARED<RobotRaconteur::DataTypeException>(err2.what()),m, ep);
}
}
void GroundProjection_skel::rr_image_coordinate(RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel, RR_SHARED_PTR<Duckiebot::Vector2D > ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::ServerEndpoint> ep)
{
if(err)
{
EndAsyncCallFunction(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),err,m, ep);
return;
}
try
{
RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel1=skel.lock();
if (!skel1) throw std::runtime_error("skel release");
RR_SHARED_PTR<RobotRaconteur::MessageElement> mr=RR_MAKE_SHARED<RobotRaconteur::MessageElement>("return",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(skel1->RRGetNode()->PackStructure(RobotRaconteur::rr_cast<RobotRaconteur::RRStructure>(ret))));
EndAsyncCallFunction(skel, mr, err, m,ep);
}
catch (RobotRaconteur::RobotRaconteurException& err2)
{
EndAsyncCallFunction(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),RobotRaconteur::RobotRaconteurExceptionUtil::DownCastException(err2),m, ep);
}
catch (std::exception& err2)
{
EndAsyncCallFunction(skel,RR_SHARED_PTR<RobotRaconteur::MessageElement>(),RR_MAKE_SHARED<RobotRaconteur::DataTypeException>(err2.what()),m, ep);
}
}
void GroundProjection_skel::rr_newSegments_Handler(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > segs)
{
RR_SHARED_PTR<RobotRaconteur::MessageEntry> rr_mm=RR_MAKE_SHARED<RobotRaconteur::MessageEntry>(RobotRaconteur::MessageEntryType_EventReq,"newSegments");
rr_mm->AddElement(RR_MAKE_SHARED<RobotRaconteur::MessageElement>("segs",RobotRaconteur::rr_cast<RobotRaconteur::MessageElementData>(RRGetNode()->PackListType<Duckiebot::Segment  >(segs))));
SendEvent(rr_mm);
}
void GroundProjection_skel::RegisterEvents(RR_SHARED_PTR<RobotRaconteur::RRObject> rrobj1)
{
RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection > obj=RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection >(rrobj1);
newSegments_rrconnection=obj->get_newSegments().connect(boost::bind(&GroundProjection_skel::rr_newSegments_Handler, RobotRaconteur::rr_cast<GroundProjection_skel>(shared_from_this()), _1));
RobotRaconteur::ServiceSkel::RegisterEvents(rrobj1);
}

void GroundProjection_skel::UnregisterEvents(RR_SHARED_PTR<RobotRaconteur::RRObject> rrobj1)
{
newSegments_rrconnection.disconnect();
RobotRaconteur::ServiceSkel::UnregisterEvents(rrobj1);
}

RR_SHARED_PTR<RobotRaconteur::RRObject> GroundProjection_skel::GetSubObj(const std::string &name, const std::string &ind)
{
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

void GroundProjection_skel::InitPipeServers(RR_SHARED_PTR<RobotRaconteur::RRObject> rrobj1)
{
if (rr_InitPipeServersRun) return;
rr_InitPipeServersRun=true;
RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection > obj=RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection >(rrobj1);
}

void GroundProjection_skel::DispatchPipeMessage(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, uint32_t e)
{
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

RR_SHARED_PTR<RobotRaconteur::MessageEntry> GroundProjection_skel::CallPipeFunction(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, uint32_t e)
{
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

void GroundProjection_skel::InitWireServers(RR_SHARED_PTR<RobotRaconteur::RRObject> rrobj1)
{
if (rr_InitWireServersRun) return;
rr_InitWireServersRun=true;
RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection > obj=RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection >(rrobj1);
}

void GroundProjection_skel::DispatchWireMessage(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, uint32_t e)
{
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

RR_SHARED_PTR<RobotRaconteur::MessageEntry> GroundProjection_skel::CallWireFunction(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, uint32_t e)
{
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

void GroundProjection_skel::InitCallbackServers(RR_SHARED_PTR<RobotRaconteur::RRObject> o)
{
RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection > obj=RobotRaconteur::rr_cast<Duckiebot::GroundProjection::GroundProjection >(o);
}
RR_SHARED_PTR<void> GroundProjection_skel::GetCallbackFunction(uint32_t endpoint, const std::string& membername)
{
throw RobotRaconteur::MemberNotFoundException("Member not found");
}

RR_SHARED_PTR<RobotRaconteur::MessageEntry> GroundProjection_skel::CallMemoryFunction(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::Endpoint> e)
{
throw RobotRaconteur::MemberNotFoundException("Member not found");
}
}
}

