//This file is automatically generated. DO NOT EDIT!

#include <RobotRaconteur.h>
#include <boost/signals2.hpp>
#include "Duckiebot.h"
#pragma once

namespace Duckiebot
{
namespace LineDetector
{

class LineDetector;

class LineDetector : public virtual RobotRaconteur::RRObject
{
public:
virtual RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > get_segments()=0;
virtual void set_segments(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value)=0;

virtual boost::signals2::signal<void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >)>& get_newSegments()=0;

virtual std::string RRType() {return "Duckiebot.LineDetector.LineDetector";  }
};

}
}

