//This file is automatically generated. DO NOT EDIT!

#include "Duckiebot__GroundProjection.h"
#include "Duckiebot_stubskel.h"
#pragma once

namespace Duckiebot
{
namespace GroundProjection
{

class Duckiebot__GroundProjectionFactory : public virtual RobotRaconteur::ServiceFactory
{
public:
virtual std::string GetServiceName();
virtual std::string DefString();
virtual RR_SHARED_PTR<RobotRaconteur::StructureStub> FindStructureStub(std::string s);
virtual RR_SHARED_PTR<RobotRaconteur::MessageElementStructure> PackStructure(RR_SHARED_PTR<RobotRaconteur::RRStructure> structin);
virtual RR_SHARED_PTR<RobotRaconteur::RRObject> UnpackStructure(RR_SHARED_PTR<RobotRaconteur::MessageElementStructure> mstructin);
virtual RR_SHARED_PTR<RobotRaconteur::ServiceStub> CreateStub(std::string objecttype, std::string path, RR_SHARED_PTR<RobotRaconteur::ClientContext> context);
virtual RR_SHARED_PTR<RobotRaconteur::ServiceSkel> CreateSkel(std::string objecttype, std::string path, RR_SHARED_PTR<RobotRaconteur::RRObject> obj, RR_SHARED_PTR<RobotRaconteur::ServerContext> context);
virtual void DownCastAndThrowException(RobotRaconteur::RobotRaconteurException& exp);
virtual RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> DownCastException(RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> exp);
};

class async_GroundProjection
{
public:
virtual void async_get_segments(boost::function<void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE) = 0;
virtual void async_set_segments(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value,boost::function<void (RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE) = 0;

#ifdef ROBOTRACONTEUR_USE_ASIO_SPAWN
virtual RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > async_get_segments(boost::asio::yield_context rr_yield, int32_t rr_timeout=RR_TIMEOUT_INFINITE)
{
    return RobotRaconteur::detail::async_wrap_for_spawn<RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > >(boost::bind((void (async_GroundProjection::*)(boost::function<void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) >, int32_t))&async_GroundProjection::async_get_segments, this, _1, rr_timeout), rr_yield);
}
virtual void async_set_segments(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value, boost::asio::yield_context rr_yield, int32_t rr_timeout=RR_TIMEOUT_INFINITE)
{
    RobotRaconteur::detail::async_wrap_for_spawn_void(boost::bind((void (async_GroundProjection::*)(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >, boost::function<void(RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>)>, int32_t))&async_GroundProjection::async_set_segments, this, boost::ref(value), _1, rr_timeout), rr_yield);
}
#endif

virtual void async_estimate_homography(RR_SHARED_PTR<Duckiebot::Image > im,boost::function<void (RR_SHARED_PTR<RobotRaconteur::RRArray<double > >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE) = 0;

#ifdef ROBOTRACONTEUR_USE_ASIO_SPAWN
RR_SHARED_PTR<RobotRaconteur::RRArray<double > > async_estimate_homography(RR_SHARED_PTR<Duckiebot::Image > im,boost::asio::yield_context rr_yield, int32_t rr_timeout=RR_TIMEOUT_INFINITE)
{
    return RobotRaconteur::detail::async_wrap_for_spawn<RR_SHARED_PTR<RobotRaconteur::RRArray<double > >>(boost::bind((void (async_GroundProjection::*)(RR_SHARED_PTR<Duckiebot::Image >,boost::function<void (RR_SHARED_PTR<RobotRaconteur::RRArray<double > >,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>)>,int32_t))&async_GroundProjection::async_estimate_homography, this, boost::ref(im),_1,rr_timeout), rr_yield);
}
#endif

virtual void async_ground_coordinate(RR_SHARED_PTR<Duckiebot::Pixel > uv, RR_SHARED_PTR<Duckiebot::Vector2D > normalized_uv,boost::function<void (RR_SHARED_PTR<Duckiebot::Point >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE) = 0;

#ifdef ROBOTRACONTEUR_USE_ASIO_SPAWN
RR_SHARED_PTR<Duckiebot::Point > async_ground_coordinate(RR_SHARED_PTR<Duckiebot::Pixel > uv, RR_SHARED_PTR<Duckiebot::Vector2D > normalized_uv,boost::asio::yield_context rr_yield, int32_t rr_timeout=RR_TIMEOUT_INFINITE)
{
    return RobotRaconteur::detail::async_wrap_for_spawn<RR_SHARED_PTR<Duckiebot::Point >>(boost::bind((void (async_GroundProjection::*)(RR_SHARED_PTR<Duckiebot::Pixel >,RR_SHARED_PTR<Duckiebot::Vector2D >,boost::function<void (RR_SHARED_PTR<Duckiebot::Point >,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>)>,int32_t))&async_GroundProjection::async_ground_coordinate, this, boost::ref(uv),boost::ref(normalized_uv),_1,rr_timeout), rr_yield);
}
#endif

virtual void async_image_coordinate(RR_SHARED_PTR<Duckiebot::Point > gp,boost::function<void (RR_SHARED_PTR<Duckiebot::Vector2D >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE) = 0;

#ifdef ROBOTRACONTEUR_USE_ASIO_SPAWN
RR_SHARED_PTR<Duckiebot::Vector2D > async_image_coordinate(RR_SHARED_PTR<Duckiebot::Point > gp,boost::asio::yield_context rr_yield, int32_t rr_timeout=RR_TIMEOUT_INFINITE)
{
    return RobotRaconteur::detail::async_wrap_for_spawn<RR_SHARED_PTR<Duckiebot::Vector2D >>(boost::bind((void (async_GroundProjection::*)(RR_SHARED_PTR<Duckiebot::Point >,boost::function<void (RR_SHARED_PTR<Duckiebot::Vector2D >,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>)>,int32_t))&async_GroundProjection::async_image_coordinate, this, boost::ref(gp),_1,rr_timeout), rr_yield);
}
#endif

};
class GroundProjection_stub : public virtual GroundProjection, public virtual async_GroundProjection, public virtual RobotRaconteur::ServiceStub
{
public:
GroundProjection_stub(const std::string& path, RR_SHARED_PTR<RobotRaconteur::ClientContext> c);

virtual void RRInitStub();
virtual RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > get_segments();
virtual void set_segments(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value);

virtual RR_SHARED_PTR<RobotRaconteur::RRArray<double > > estimate_homography(RR_SHARED_PTR<Duckiebot::Image > im);

virtual RR_SHARED_PTR<Duckiebot::Point > ground_coordinate(RR_SHARED_PTR<Duckiebot::Pixel > uv, RR_SHARED_PTR<Duckiebot::Vector2D > normalized_uv);

virtual RR_SHARED_PTR<Duckiebot::Vector2D > image_coordinate(RR_SHARED_PTR<Duckiebot::Point > gp);

virtual boost::signals2::signal<void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >)>& get_newSegments();


virtual void DispatchEvent(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m);
virtual void DispatchPipeMessage(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m);
virtual void DispatchWireMessage(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m);
virtual RR_SHARED_PTR<RobotRaconteur::MessageEntry> CallbackCall(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m);
virtual void RRClose();
private:
boost::signals2::signal<void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >)> rrvar_newSegments;

virtual void async_get_segments(boost::function<void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > >,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE);
virtual void async_set_segments(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value,boost::function<void (RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE);

protected:
virtual void rrend_get_segments(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > ,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler);
virtual void rrend_set_segments(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler);
public:
virtual void async_estimate_homography(RR_SHARED_PTR<Duckiebot::Image > im,boost::function<void (RR_SHARED_PTR<RobotRaconteur::RRArray<double > >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE);

protected:
virtual void rrend_estimate_homography(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<RobotRaconteur::RRArray<double > > ,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler);
public:
virtual void async_ground_coordinate(RR_SHARED_PTR<Duckiebot::Pixel > uv, RR_SHARED_PTR<Duckiebot::Vector2D > normalized_uv,boost::function<void (RR_SHARED_PTR<Duckiebot::Point >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE);

protected:
virtual void rrend_ground_coordinate(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<Duckiebot::Point > ,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler);
public:
virtual void async_image_coordinate(RR_SHARED_PTR<Duckiebot::Point > gp,boost::function<void (RR_SHARED_PTR<Duckiebot::Vector2D >, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > rr_handler, int32_t rr_timeout=RR_TIMEOUT_INFINITE);

protected:
virtual void rrend_image_coordinate(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, boost::function< void (RR_SHARED_PTR<Duckiebot::Vector2D > ,RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException>) > handler);
public:
virtual std::string RRType();
};


class GroundProjection_skel : public virtual RobotRaconteur::ServiceSkel
{
public:
virtual void Init(const std::string& path, RR_SHARED_PTR<RobotRaconteur::RRObject> object, RR_SHARED_PTR<RobotRaconteur::ServerContext> context);
virtual RR_SHARED_PTR<RobotRaconteur::MessageEntry> CallGetProperty(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m);

virtual RR_SHARED_PTR<RobotRaconteur::MessageEntry> CallSetProperty(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m);

virtual RR_SHARED_PTR<RobotRaconteur::MessageEntry> CallFunction(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m);

virtual void ReleaseCastObject();

virtual void RegisterEvents(RR_SHARED_PTR<RobotRaconteur::RRObject> rrobj1);

virtual void UnregisterEvents(RR_SHARED_PTR<RobotRaconteur::RRObject> rrobj1);

virtual RR_SHARED_PTR<RobotRaconteur::RRObject> GetSubObj(const std::string &name, const std::string &ind);

virtual void InitPipeServers(RR_SHARED_PTR<RobotRaconteur::RRObject> rrobj1);

virtual void InitWireServers(RR_SHARED_PTR<RobotRaconteur::RRObject> rrobj1);

virtual void DispatchPipeMessage(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, uint32_t e);

virtual void DispatchWireMessage(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, uint32_t e);

virtual void InitCallbackServers(RR_SHARED_PTR<RobotRaconteur::RRObject> o);

virtual RR_SHARED_PTR<RobotRaconteur::MessageEntry> CallPipeFunction(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, uint32_t e);

virtual RR_SHARED_PTR<RobotRaconteur::MessageEntry> CallWireFunction(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, uint32_t e);

virtual RR_SHARED_PTR<void> GetCallbackFunction(uint32_t endpoint, const std::string& membername);

virtual RR_SHARED_PTR<RobotRaconteur::MessageEntry> CallMemoryFunction(RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::Endpoint> e);

virtual std::string GetObjectType();
virtual RR_SHARED_PTR<Duckiebot::GroundProjection::GroundProjection > get_obj();

virtual RR_SHARED_PTR<Duckiebot::GroundProjection::async_GroundProjection > get_asyncobj();

protected:
static void rr_get_segments(RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel, RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > value, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::ServerEndpoint> ep);
static void rr_estimate_homography(RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel, RR_SHARED_PTR<RobotRaconteur::RRArray<double > > ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::ServerEndpoint> ep);
static void rr_ground_coordinate(RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel, RR_SHARED_PTR<Duckiebot::Point > ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::ServerEndpoint> ep);
static void rr_image_coordinate(RR_WEAK_PTR<Duckiebot::GroundProjection::GroundProjection_skel> skel, RR_SHARED_PTR<Duckiebot::Vector2D > ret, RR_SHARED_PTR<RobotRaconteur::RobotRaconteurException> err, RR_SHARED_PTR<RobotRaconteur::MessageEntry> m, RR_SHARED_PTR<RobotRaconteur::ServerEndpoint> ep);
 public:
void rr_newSegments_Handler(RR_SHARED_PTR<RobotRaconteur::RRList<Duckiebot::Segment  > > segs);
protected:boost::signals2::connection newSegments_rrconnection;
bool rr_InitPipeServersRun;
bool rr_InitWireServersRun;
public: 
private:

};

}
}

