//This file is automatically generated. DO NOT EDIT!

#include <RobotRaconteur.h>
#include <boost/signals2.hpp>
#pragma once

namespace Duckiebot
{
namespace Drive
{

class Drive;

class Drive : public virtual RobotRaconteur::RRObject
{
public:
virtual uint8_t get_eStop()=0;
virtual void set_eStop(uint8_t value)=0;

virtual double get_gain()=0;
virtual void set_gain(double value)=0;

virtual double get_trim()=0;
virtual void set_trim(double value)=0;

virtual double get_baseline()=0;
virtual void set_baseline(double value)=0;

virtual double get_radius()=0;
virtual void set_radius(double value)=0;

virtual double get_k()=0;
virtual void set_k(double value)=0;

virtual double get_limit()=0;
virtual void set_limit(double value)=0;

virtual void wheelCmd(double vL, double vR)=0;

virtual void carCmd(double v, double omega)=0;

virtual void toggleEStop()=0;

virtual void resetParams()=0;

virtual std::string RRType() {return "Duckiebot.Drive.Drive";  }
};

}
}

